name: Aspect Workflows

on:
    pull_request:

jobs:
    aspect-workflows:
        name: Aspect Workflows
        uses: alexeagle/workflows-action/.github/workflows/.aspect-workflows-reusable.yaml@a331d3a1327acbba132699787824f258c50100e7
