on:
  schedule:
    # Mondays at 5am UTC / midnight EST
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: tag repo
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/git/refs \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data @- << EOF
          {
            "ref": "refs/tags/$(date +%Y.%V)",
            "sha": "$(git rev-parse HEAD)"
          }
          EOF
