on:
  schedule:
    # Mondays at 5am UTC / midnight EST
    - cron: '0 5 * * 1'
  # Allow manual triggering in GH web UI
  workflow_dispatch:

jobs:
  tagger:
    runs-on: ubuntu-latest
    steps:
      - name: tag HEAD with date +%Y.%V
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/git/refs \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --data @- << EOF
          {
            "ref": "refs/tags/$(date +%Y.%V)",
            "sha": "${{ github.sha }}"
          }
          EOF
